import type { CoinSubmission, Project, ProjectStatus } from "./types";

const API_BASE = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "https://solpitchswap.kevingpersson.workers.dev";
type ApiError = { error?: string };
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`${API_BASE}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", ...(init.headers ?? {}) } }); const body = await response.json().catch(() => ({})) as T & ApiError; if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }

export type TokenAnalysis = { found:boolean; address:string; tradable:boolean; name?:string; symbol?:string; logoUrl?:string; website?:string; xUrl?:string; telegramUrl?:string; dexScreenerUrl?:string; dexId?:string; pairAddress?:string; priceUsd?:string; liquidityUsd?:number; marketCap?:number; volume24h?:number; metadataFound?:number; metadataTotal?:number; analysisLevel?:"strong"|"review"|"manual"; description?:string; pitch?:string; metadataSource?:string; descriptionFound?:boolean };
export type ClaimRequest = { id:string; projectName:string; projectSymbol:string; projectSlug:string; walletAddress:string; evidenceUrl:string; submitterEmail:string; createdAt:string };
export type ActivityEvent = { id:string; projectId?:string; eventType:string; eventText:string; createdAt:string; slug?:string; name?:string; symbol?:string; logoUrl?:string };
export type SubmissionPayload = { name:string; symbol:string; contractAddress:string; projectStatus:ProjectStatus; pitch:string; description:string; website?:string; xUrl?:string; telegramUrl?:string; logoUrl?:string; statusProofUrl:string; submitterEmail:string; turnstileToken?:string };

export async function analyzeToken(address:string){return request<TokenAnalysis>(`/api/analyze-token?address=${encodeURIComponent(address)}`);}
export async function getPublishedProjects(){const result=await request<{projects:Record<string,unknown>[]}>('/api/projects');return result.projects.map(mapProjectRow);}
export async function getActivity(){const result=await request<{events:Record<string,unknown>[]}>('/api/activity');return result.events.map(row=>({id:String(row.id),projectId:String(row.project_id??'')||undefined,eventType:String(row.event_type),eventText:String(row.event_text),createdAt:String(row.created_at),slug:String(row.slug??'')||undefined,name:String(row.name??'')||undefined,symbol:String(row.symbol??'')||undefined,logoUrl:String(row.logo_url??'')||undefined}));}
export async function submitCoin(payload:SubmissionPayload){return request<{id:string;status:"pending";projectStatus:ProjectStatus}>('/api/submissions',{method:'POST',body:JSON.stringify(payload)});}
export async function createClaimNonce(projectSlug:string,walletAddress:string){return request<{nonce:string;message:string}>('/api/claims/nonce',{method:'POST',body:JSON.stringify({projectSlug,walletAddress})});}
export async function submitClaim(payload:{nonce:string;walletAddress:string;signature:string;evidenceUrl?:string;submitterEmail?:string}){return request<{id:string;status:"pending"}>('/api/claims',{method:'POST',body:JSON.stringify(payload)});}
export async function createVoteNonce(projectSlug:string,walletAddress:string){return request<{nonce:string;message:string;weekKey:string}>('/api/votes/nonce',{method:'POST',body:JSON.stringify({projectSlug,walletAddress})});}
export async function submitVote(payload:{nonce:string;walletAddress:string;signature:string}){return request<{ok:true;votes:number;weekKey:string}>('/api/votes',{method:'POST',body:JSON.stringify(payload)});}
export async function adminLogin(password:string){return request<{ok:true}>('/api/admin/login',{method:'POST',body:JSON.stringify({password})});}
export async function adminLogout(){return request<{ok:true}>('/api/admin/logout',{method:'POST',body:'{}'});}
export async function getAdminSession(){return request<{authenticated:boolean}>('/api/admin/session');}
export async function getPendingSubmissions(){const result=await request<{submissions:Record<string,unknown>[]}>('/api/admin/submissions?status=pending');return result.submissions.map(mapSubmissionRow);}
export async function getPendingClaims(){const result=await request<{claims:Record<string,unknown>[]}>('/api/admin/claims');return result.claims.map(row=>({id:String(row.id),projectName:String(row.project_name),projectSymbol:String(row.project_symbol),projectSlug:String(row.project_slug),walletAddress:String(row.wallet_address),evidenceUrl:String(row.evidence_url??''),submitterEmail:String(row.submitter_email??''),createdAt:String(row.created_at)}));}
export async function reviewSubmission(id:string,status:"approved"|"rejected",reviewerNotes:string,options:{addedToSwap?:boolean;promoted?:boolean;logoUrl?:string}={}){return request<{ok:true}>(`/api/admin/submissions/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status,reviewerNotes,...options})});}
export async function reviewClaim(id:string,status:"approved"|"rejected",reviewerNotes:string){return request<{ok:true}>(`/api/admin/claims/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status,reviewerNotes})});}

function mapProjectRow(row:Record<string,unknown>):Project{const promoted=Number(row.promoted??0)===1;return{slug:String(row.slug),name:String(row.name),symbol:String(row.symbol),contractAddress:String(row.contract_address),projectStatus:String(row.project_status) as ProjectStatus,claimStatus:String(row.claim_status??'unclaimed') as Project['claimStatus'],pitch:String(row.pitch),description:String(row.description),badges:promoted?["Community Listed","Featured"]:["Community Listed"],logoURI:String(row.logo_url??'')||undefined,marketCap:'Live data soon',liquidity:'Live data soon',volume24h:'Live data soon',holders:'Live data soon',votes:Number(row.votes??0),listedLabel:new Date(String(row.published_at)).toLocaleDateString(),links:{website:String(row.website??'')||undefined,x:String(row.x_url??'')||undefined,telegram:String(row.telegram_url??'')||undefined}};}
function mapSubmissionRow(row:Record<string,unknown>):CoinSubmission{return{id:String(row.id),name:String(row.name),symbol:String(row.symbol),contractAddress:String(row.contract_address),projectStatus:String(row.project_status) as ProjectStatus,pitch:String(row.pitch),description:String(row.description),website:String(row.website??''),x:String(row.x_url??''),telegram:String(row.telegram_url??''),statusProof:String(row.status_proof_url),submitterEmail:String(row.submitter_email??''),reviewerNote:String(row.reviewer_notes??''),status:String(row.status) as CoinSubmission['status'],submittedAt:String(row.created_at)};}
