import { FormEvent, useEffect, useMemo, useState } from "react";
import { adminLogin, adminLogout, getAdminSession, getPendingSubmissions, reviewSubmission, submitCoin } from "./api";
import { mostVoted, projects, promoted } from "./data";
import type { CoinSubmission, Project, ProjectBadge, ProjectStatus } from "./types";
import "./styles.css";

const SWAP_URL = "https://solpitch.net";
type View = "listings" | "submit" | "admin";
const statusLabels: Record<ProjectStatus,string> = { graduated:"Graduated", bonding:"Bonding", launched:"New Launch", presale:"Presale", upcoming:"Upcoming" };
const tradableStatuses: ProjectStatus[] = ["graduated","bonding","launched"];

function Badge({ badge }: { badge: ProjectBadge }) { return <span className={`badge badge-${badge.toLowerCase()}`}>{badge}</span>; }

function LeftNavigation({ view, onView }: { view: View; onView: (view: View) => void }) {
  return <aside className="left-sidebar panel"><button className="brand brand-button" onClick={()=>onView("listings")}><span className="brand-mark">SP</span><span><strong>SolPitch</strong><small>All Solana project stages</small></span></button><nav><button className={view==="listings"?"active":""} onClick={()=>onView("listings")}><span className="nav-dot"/>All Listings</button>{["Graduated","Bonding","New Launches","Presales","Upcoming","Most Voted","Promoted"].map(item=><button onClick={()=>onView("listings")} key={item}><span className="nav-dot"/>{item}</button>)}</nav><p className="nav-label">PROJECT TOOLS</p><nav><button className={view==="submit"?"active":""} onClick={()=>onView("submit")}><span className="nav-dot"/>Submit Coin</button><button onClick={()=>onView("listings")}><span className="nav-dot"/>Advertise</button><button className={view==="admin"?"active":""} onClick={()=>onView("admin")}><span className="nav-dot"/>Admin Review</button></nav><div className="rule-card"><strong>Every status must be explicit.</strong><span>No misleading launch claims, hidden presales or fake graduation labels.</span></div></aside>;
}

function ProjectCard({ project,onOpen }:{ project:Project; onOpen:(project:Project)=>void }) {
  const tradable=tradableStatuses.includes(project.projectStatus);
  return <article className="project-card panel"><div className="project-top"><div className="project-logo">{project.name[0]}</div><div className="project-heading"><div className="name-line"><h3>{project.name}</h3><span>${project.symbol}</span></div><div className="badges"><span className={`badge badge-${project.projectStatus}`}>{statusLabels[project.projectStatus]}</span>{project.badges.filter(b=>b.toLowerCase()!==project.projectStatus).map(b=><Badge key={b} badge={b}/>)}</div></div><button className="vote-button">▲ {project.votes}</button></div><p className="pitch">{project.pitch}</p><button className="contract" onClick={()=>navigator.clipboard?.writeText(project.contractAddress)}>{project.contractAddress.slice(0,8)}...{project.contractAddress.slice(-6)} <span>Copy CA</span></button><div className="metrics">{[["Status",statusLabels[project.projectStatus]],["Market cap",project.marketCap],["Liquidity",project.liquidity],["24h volume",project.volume24h],["Votes",String(project.votes)]].map(([l,v])=><div className="metric" key={l}><small>{l}</small><strong>{v}</strong></div>)}</div><div className="project-actions"><div className="socials"><span>WEB</span><span>X</span><span>TG</span></div><div><button onClick={()=>onOpen(project)}>View Project</button>{tradable?<a href={SWAP_URL}>Swap</a>:<button disabled>Not trading yet</button>}</div></div></article>;
}

function RightSidebar() { return <aside className="right-sidebar"><section className="swap-card panel"><div className="card-heading"><div><small>SOLPITCH</small><h2>Swap</h2></div><span>Live projects only</span></div><div className="token-box"><small>You pay</small><div><strong>0.00</strong><span>◎ SOL</span></div></div><div className="swap-arrow">↓</div><div className="token-box"><small>You receive</small><div><strong>0.00</strong><span>Select token</span></div></div><a className="primary-action" href={SWAP_URL}>Open live swap</a><p className="fine-print">Presale and upcoming listings never show a working swap action.</p></section><section className="side-card panel"><div className="card-heading"><h2>Promoted</h2><span>Clearly labeled</span></div>{promoted.map(p=><div className="mini-project" key={p.slug}><span>{p.name[0]}</span><div><strong>{p.name}</strong><small>{statusLabels[p.projectStatus]}</small></div><em>Featured</em></div>)}</section><section className="side-card panel"><div className="card-heading"><h2>Most voted</h2><span>24h</span></div>{mostVoted.map((p,i)=><div className="rank-row" key={p.slug}><b>{i+1}</b><span>{p.name[0]}</span><div><strong>{p.name}</strong><small>{statusLabels[p.projectStatus]}</small></div><em>▲ {p.votes}</em></div>)}</section></aside>; }

function SubmissionForm() {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=event.currentTarget;const data=new FormData(form);try{await submitCoin({name:String(data.get("name")||""),symbol:String(data.get("symbol")||"").replace(/^\$/,""),contractAddress:String(data.get("contractAddress")||""),projectStatus:String(data.get("projectStatus")) as ProjectStatus,pitch:String(data.get("pitch")||""),description:String(data.get("description")||""),website:String(data.get("website")||""),xUrl:String(data.get("x")||""),telegramUrl:String(data.get("telegram")||""),statusProofUrl:String(data.get("statusProof")||""),submitterEmail:String(data.get("email")||"")});form.reset();setMessage("Submission received and sent to the secured admin queue.");}catch(error){setMessage(error instanceof Error?error.message:"Submission failed.");}finally{setBusy(false);}}
  return <main className="workflow-page"><header className="feed-header"><div><small>PROJECT SUBMISSION</small><h1>List a Solana project.</h1><p>Graduated, bonding, launched, presale and upcoming projects are accepted when their status is honest and verifiable.</p></div></header>{message&&<div className="success panel">{message}</div>}<form className="submission-form panel" onSubmit={submit}><div className="form-grid"><label>Coin name<input name="name" required maxLength={80}/></label><label>Ticker<input name="symbol" required maxLength={16}/></label><label>Project status<select name="projectStatus" required defaultValue="launched"><option value="graduated">Graduated</option><option value="bonding">Bonding</option><option value="launched">New Launch</option><option value="presale">Presale</option><option value="upcoming">Upcoming</option></select></label><label>Submitter email<input name="email" type="email" required/></label><label className="full">Contract address<input name="contractAddress" required minLength={32}/></label><label className="full">Short pitch<input name="pitch" required maxLength={300}/></label><label className="full">Full description<textarea name="description" required rows={5} maxLength={5000}/></label><label>Website<input name="website" type="url"/></label><label>X profile<input name="x" type="url"/></label><label>Telegram<input name="telegram" type="url"/></label><label>Status proof URL<input name="statusProof" type="url" required/></label></div><label className="check-row"><input type="checkbox" required/> I confirm the selected project status is accurate and not misleading.</label><button disabled={busy} className="primary-action form-submit" type="submit">{busy?"Submitting...":"Send for review"}</button></form></main>;
}

function AdminReview(){const[authenticated,setAuthenticated]=useState(false);const[submissions,setSubmissions]=useState<CoinSubmission[]>([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);async function refresh(){setLoading(true);try{const session=await getAdminSession();setAuthenticated(session.authenticated);if(session.authenticated)setSubmissions(await getPendingSubmissions());}catch{setAuthenticated(false);}finally{setLoading(false);}}useEffect(()=>{void refresh();},[]);async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{await adminLogin(String(data.get("password")||""));await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Login failed.");}}async function decide(id:string,status:"approved"|"rejected"){const note=(document.getElementById(`note-${id}`) as HTMLTextAreaElement)?.value??"";try{await reviewSubmission(id,status,note);await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Review failed.");}}if(loading)return <main className="workflow-page"><div className="empty panel">Loading secured admin workspace...</div></main>;if(!authenticated)return <main className="workflow-page"><header className="feed-header"><div><small>SECURED ADMIN</small><h1>Admin sign in</h1><p>Review access requires the server-side admin password.</p></div></header>{message&&<div className="success panel">{message}</div>}<form className="admin-login panel" onSubmit={login}><label>Password<input name="password" type="password" required/></label><button className="primary-action" type="submit">Sign in</button></form></main>;return <main className="workflow-page"><header className="feed-header"><div><small>ADMIN WORKSPACE</small><h1>Submission review queue</h1><p>{submissions.length} project{submissions.length===1?"":"s"} awaiting review.</p></div><button onClick={async()=>{await adminLogout();setAuthenticated(false);}}>Sign out</button></header>{submissions.map(s=><article className="review-card panel" key={s.id}><div className="review-heading"><div><h2>{s.name} <span>${s.symbol}</span></h2><small>{statusLabels[s.projectStatus]} • Submitted {new Date(s.submittedAt).toLocaleString()}</small></div><span className={`badge badge-${s.projectStatus}`}>{statusLabels[s.projectStatus]}</span></div><p>{s.pitch}</p><dl><div><dt>Contract</dt><dd>{s.contractAddress}</dd></div><div><dt>Submitter</dt><dd>{s.submitterEmail}</dd></div><div><dt>Status proof</dt><dd><a href={s.statusProof} target="_blank" rel="noreferrer">Open evidence</a></dd></div></dl><textarea id={`note-${s.id}`} placeholder="Reviewer note" rows={3}/><div className="decision-row"><button className="reject" onClick={()=>void decide(s.id,"rejected")}>Reject</button><button className="approve" onClick={()=>void decide(s.id,"approved")}>Approve listing</button></div></article>)}</main>;}

function ProjectPage({project,onBack}:{project:Project;onBack:()=>void}){const tradable=tradableStatuses.includes(project.projectStatus);return <main className="project-page"><button className="back-button" onClick={onBack}>← Back to listings</button><section className="project-hero panel"><div className="project-logo large">{project.name[0]}</div><div><div className="name-line"><h1>{project.name}</h1><span>${project.symbol}</span></div><div className="badges"><span className={`badge badge-${project.projectStatus}`}>{statusLabels[project.projectStatus]}</span>{project.badges.map(b=><Badge key={b} badge={b}/>)}</div><p>{project.description}</p></div></section><section className="detail-grid"><div className="panel detail-card"><small>CONTRACT ADDRESS</small><strong>{project.contractAddress}</strong><button onClick={()=>navigator.clipboard?.writeText(project.contractAddress)}>Copy address</button></div><div className="panel detail-card"><small>PROJECT STATUS</small><strong>{statusLabels[project.projectStatus]}</strong>{tradable?<a href={SWAP_URL}>Trade on SolPitch</a>:<span>Trading not available yet</span>}</div></section></main>;}

export default function App(){const[query,setQuery]=useState("");const[selected,setSelected]=useState<Project|null>(null);const[view,setView]=useState<View>("listings");const[statusFilter,setStatusFilter]=useState<"all"|ProjectStatus>("all");const filtered=useMemo(()=>projects.filter(p=>(statusFilter==="all"||p.projectStatus===statusFilter)&&`${p.name} ${p.symbol} ${p.contractAddress}`.toLowerCase().includes(query.toLowerCase())),[query,statusFilter]);const changeView=(next:View)=>{setSelected(null);setView(next);};return <div className="app"><header className="topbar"><button className="mobile-brand" onClick={()=>changeView("listings")}>SolPitch</button><input value={query} onChange={e=>setQuery(e.target.value)} disabled={view!=="listings"||Boolean(selected)} placeholder="Search Solana projects, tickers or contract addresses"/><div><button>Advertise</button><button className="top-primary" onClick={()=>changeView("submit")}>Submit Coin</button></div></header><div className="layout"><LeftNavigation view={view} onView={changeView}/>{selected?<ProjectPage project={selected} onBack={()=>setSelected(null)}/>:view==="submit"?<SubmissionForm/>:view==="admin"?<AdminReview/>:<main className="feed"><header className="feed-header"><div><small>SOLANA PROJECT DIRECTORY</small><h1>Discover projects at every stage.</h1><p>Every listing shows its exact status so users know what is live, bonding, in presale or upcoming.</p></div><button>Newest first ▾</button></header><div className="filters">{(["all","graduated","bonding","launched","presale","upcoming"] as const).map(status=><button className={statusFilter===status?"active":""} onClick={()=>setStatusFilter(status)} key={status}>{status==="all"?"All listings":statusLabels[status]}</button>)}</div>{filtered.map(p=><ProjectCard project={p} onOpen={setSelected} key={p.slug}/>)}{filtered.length===0&&<div className="empty panel">No approved projects match that filter.</div>}</main>}<RightSidebar/></div></div>;}
