import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "toez",
    name: "TOEZ",
    symbol: "TOEZ",
    contractAddress: "3DRCui7ZbEykhrUHMbyXSvn5731fbKchFTFvs1Wjpump",
    projectStatus: "graduated",
    claimStatus: "unclaimed",
    pitch: "A Solana community project previously added to SolPitch Swap and now ready to be claimed by its official team.",
    description: "TOEZ is a community-listed Solana project. This page uses public token information and has not yet been claimed by the official project team.",
    badges: ["Community Listed"],
    logoURI: "https://ipfs.io/ipfs/QmQojwpFsx6GQeFkVxL87fcKVKacchjbEDWqXuPDcg5uJu",
    marketCap: "Live data soon",
    liquidity: "Live data soon",
    volume24h: "Live data soon",
    holders: "Live data soon",
    votes: 178,
    listedLabel: "SolPitch original",
    links: {},
  },
  {
    slug: "bonk",
    name: "Bonk",
    symbol: "BONK",
    contractAddress: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    projectStatus: "graduated",
    claimStatus: "unclaimed",
    pitch: "One of Solana’s most recognized community tokens, added as an unclaimed public-information listing.",
    description: "BONK is listed using public token information. The official project team has not claimed or endorsed this SolPitch page.",
    badges: ["Community Listed", "Trending"],
    logoURI: "https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I",
    marketCap: "Live data soon",
    liquidity: "Live data soon",
    volume24h: "Live data soon",
    holders: "Live data soon",
    votes: 162,
    listedLabel: "Community seed",
    links: {},
  },
  {
    slug: "dogwifhat",
    name: "dogwifhat",
    symbol: "WIF",
    contractAddress: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    projectStatus: "graduated",
    claimStatus: "unclaimed",
    pitch: "A widely recognized Solana memecoin, community-listed and claimable by its verified project team.",
    description: "dogwifhat is listed using public token information. The official project team has not claimed or endorsed this SolPitch page.",
    badges: ["Community Listed"],
    logoURI: "https://bafkreibk3covs5ltyqxa272uodhculbr6kea6betidfwy3ajsav2vjzyum.ipfs.nftstorage.link",
    marketCap: "Live data soon",
    liquidity: "Live data soon",
    volume24h: "Live data soon",
    holders: "Live data soon",
    votes: 149,
    listedLabel: "Community seed",
    links: {},
  },
  {
    slug: "popcat",
    name: "Popcat",
    symbol: "POPCAT",
    contractAddress: "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    projectStatus: "graduated",
    claimStatus: "unclaimed",
    pitch: "A popular Solana community token with a claimable SolPitch project page.",
    description: "POPCAT is listed using public token information. The official project team has not claimed or endorsed this SolPitch page.",
    badges: ["Community Listed"],
    logoURI: "https://arweave.net/A1etRNMKxhlNGTf-gNBtJ75QJJ4NJtbKh_UXQTlLXzI",
    marketCap: "Live data soon",
    liquidity: "Live data soon",
    volume24h: "Live data soon",
    holders: "Live data soon",
    votes: 137,
    listedLabel: "Community seed",
    links: {},
  },
];

export const promoted = projects.filter(project => project.badges.includes("Featured"));
export const mostVoted = [...projects].sort((a, b) => b.votes - a.votes);
