import { useEffect, useMemo, useRef, useState } from "react";
import { Buffer } from "buffer";
import { VersionedTransaction } from "@solana/web3.js";
import "./native-swap.css";

if (!(globalThis as { Buffer?: typeof Buffer }).Buffer) (globalThis as { Buffer?: typeof Buffer }).Buffer = Buffer;

type SwapToken = { symbol:string; name:string; mint:string; decimals:number; logoURI?:string };
type Quote = { inAmount:string; outAmount:string; priceImpactPct?:string; routePlan?:unknown[] } & Record<string, unknown>;
type SwapPhantomProvider = { isPhantom?:boolean; publicKey?:{toString():string}; connect():Promise<{publicKey:{toString():string}}>; signAndSendTransaction?(tx:VersionedTransaction):Promise<{signature:string}|string>; signTransaction?(tx:VersionedTransaction):Promise<VersionedTransaction> };

declare global { interface Window { phantom?:{solana?:SwapPhantomProvider} } }

const SOL:SwapToken={symbol:"SOL",name:"Solana",mint:"So11111111111111111111111111111111111111112",decimals:9,logoURI:"https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png"};
const USDC:SwapToken={symbol:"USDC",name:"USD Coin",mint:"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",decimals:6,logoURI:"https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png"};
const PRESET_TOKENS:SwapToken[]=[
 SOL,
 USDC,
 {symbol:"JUP",name:"Jupiter",mint:"JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",decimals:6,logoURI:"https://static.jup.ag/jup/icon.png"},
 {symbol:"BONK",name:"Bonk",mint:"DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",decimals:5,logoURI:"https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I"},
 {symbol:"WIF",name:"dogwifhat",mint:"EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",decimals:6,logoURI:"https://bafkreibk3covs5ltyqxa272uodhculbr6kea6betidfwy3ajsav2vjzyum.ipfs.nftstorage.link"},
 {symbol:"POPCAT",name:"Popcat",mint:"7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",decimals:9,logoURI:"https://arweave.net/A1etRNMKxhlNGTf-gNBtJ75QJJ4NJtbKh_UXQTlLXzI"},
 {symbol:"MOODENG",name:"Moo Deng",mint:"ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",decimals:6,logoURI:"https://ipfs.io/ipfs/Qmf1g7dJZNDJHRQru7E7ENwDjcvu7swMUB6x9ZqPXr4RV2"},
 {symbol:"PNUT",name:"Peanut the Squirrel",mint:"2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",decimals:6,logoURI:"https://ipfs.io/ipfs/QmNdTtJauw39u4DzGyTaZ35rRx4VgAxqb91wE89zjyHWd2"},
 {symbol:"ONYX",name:"Onyx Kitty",mint:"5uHh5i8KUHmu6334mcQpc6FejLuoJQSjJZYPgQ8cpump",decimals:6,logoURI:"https://ipfs.io/ipfs/bafkreibw4ewc2pi2muwgsnwt3uc6wapmzlsmy24h5if2ta27anysqf4p6i"},
 {symbol:"TOEZ",name:"TOEZ",mint:"3DRCui7ZbEykhrUHMbyXSvn5731fbKchFTFvs1Wjpump",decimals:6,logoURI:"https://ipfs.io/ipfs/QmQojwpFsx6GQeFkVxL87fcKVKacchjbEDWqXuPDcg5uJu"},
 {symbol:"FARTCOIN",name:"Fartcoin",mint:"9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",decimals:6,logoURI:"https://coin-images.coingecko.com/coins/images/50891/small/fart.jpg?1729503972"},
 {symbol:"GOAT",name:"Goatseus Maximus",mint:"CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",decimals:6,logoURI:"https://ipfs.io/ipfs/QmapAq9WtNrtyaDtjZPAHHNYmpSZAQU6HywwvfSWq4dQVV"},
];
const API_BASE=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,"")??"https://solpitchswap.kevingpersson.workers.dev";

function provider(){return (window.phantom?.solana??(window as unknown as {solana?:SwapPhantomProvider}).solana) as SwapPhantomProvider|undefined;}
function toRaw(value:string,decimals:number){const [whole="0",fraction=""]=value.split(".");return (BigInt(whole||"0")*10n**BigInt(decimals)+BigInt(fraction.slice(0,decimals).padEnd(decimals,"0")||"0")).toString();}
function fromRaw(value:string,decimals:number){const padded=value.padStart(decimals+1,"0");const whole=padded.slice(0,-decimals)||"0";const fraction=padded.slice(-decimals).replace(/0+$/g,"");return fraction?`${whole}.${fraction}`:whole;}
function compact(value:string){const n=Number(value);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:6}):"0";}
function findPreset(mint:string){return PRESET_TOKENS.find(token=>token.mint===mint);}

export default function NativeSwapCard(){
 const [from,setFrom]=useState<SwapToken>(SOL); const [to,setTo]=useState<SwapToken>(USDC); const [amount,setAmount]=useState("0.1"); const [quote,setQuote]=useState<Quote|null>(null); const [loading,setLoading]=useState(false); const [swapping,setSwapping]=useState(false); const [wallet,setWallet]=useState(""); const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [slippage,setSlippage]=useState(50); const debounce=useRef<number|undefined>(undefined);
 const output=useMemo(()=>quote?fromRaw(String(quote.outAmount),to.decimals):"",[quote,to.decimals]);
 useEffect(()=>{window.clearTimeout(debounce.current);setQuote(null);if(!amount||Number(amount)<=0||from.mint===to.mint)return;debounce.current=window.setTimeout(async()=>{setLoading(true);setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/quote?inputMint=${from.mint}&outputMint=${to.mint}&amount=${toRaw(amount,from.decimals)}&slippageBps=${slippage}`);const body=await response.json() as Quote&{error?:string};if(!response.ok)throw new Error(body.error||"Quote unavailable");setQuote(body);}catch(error){setMessage(error instanceof Error?error.message:"Quote unavailable");}finally{setLoading(false);}},350);return()=>window.clearTimeout(debounce.current);},[amount,from,to,slippage]);
 async function connect(){const phantom=provider();if(!phantom?.isPhantom){setMessage("Phantom was not detected.");return;}try{const result=await phantom.connect();setWallet(result.publicKey.toString());setMessage("");}catch{setMessage("Wallet connection was cancelled.");}}
 async function findToken(){const mint=search.trim();if(!mint)return;setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/token?mint=${encodeURIComponent(mint)}`);const body=await response.json() as SwapToken&{error?:string};if(!response.ok)throw new Error(body.error||"Token not found");setTo(body);setSearch("");setQuote(null);}catch(error){setMessage(error instanceof Error?error.message:"Token not found");}}
 async function execute(){if(!quote){setMessage("Enter an amount and wait for a quote.");return;}const phantom=provider();if(!phantom||!wallet){await connect();return;}setSwapping(true);setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/build`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteResponse:quote,userPublicKey:wallet})});const body=await response.json() as {swapTransaction?:string;error?:string};if(!response.ok||!body.swapTransaction)throw new Error(body.error||"Swap transaction unavailable");const tx=VersionedTransaction.deserialize(Buffer.from(body.swapTransaction,"base64"));let signature="";if(phantom.signAndSendTransaction){const sent=await phantom.signAndSendTransaction(tx);signature=typeof sent==="string"?sent:sent.signature;}else if(phantom.signTransaction){const signed=await phantom.signTransaction(tx);const sent=await fetch(`${API_BASE}/api/swap/send`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signedTransaction:Buffer.from(signed.serialize()).toString("base64")})});const result=await sent.json() as {signature?:string;error?:string};if(!sent.ok||!result.signature)throw new Error(result.error||"Transaction submission failed");signature=result.signature;}else throw new Error("Phantom cannot sign this transaction.");setMessage(`Swap submitted: ${signature.slice(0,8)}…${signature.slice(-8)}`);setAmount("");setQuote(null);}catch(error){setMessage(error instanceof Error?error.message:"Swap failed");}finally{setSwapping(false);}}
 function reverse(){setFrom(to);setTo(from);setQuote(null);}
 function chooseFrom(mint:string){const token=findPreset(mint);if(token){setFrom(token);if(token.mint===to.mint)setTo(token.mint===SOL.mint?USDC:SOL);setQuote(null);}}
 function chooseTo(mint:string){const token=findPreset(mint);if(token){setTo(token);if(token.mint===from.mint)setFrom(token.mint===SOL.mint?USDC:SOL);setQuote(null);}}
 return <section className="native-swap-card"><div className="native-swap-heading"><div><span>SOLPITCH</span><h2>Swap</h2></div><select value={slippage} onChange={e=>setSlippage(Number(e.target.value))}><option value={50}>0.5%</option><option value={100}>1%</option><option value={200}>2%</option></select></div><label className="native-ca-label">Paste CA to select token</label><div className="native-ca-row"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void findToken();}}} placeholder="Solana contract address"/><button onClick={()=>void findToken()}>Find</button></div><div className="native-token-box"><div><small>You pay</small><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,""))} placeholder="0.00" inputMode="decimal"/></div><select className="native-token-select" value={from.mint} onChange={e=>chooseFrom(e.target.value)} aria-label="Token to pay"><option value={SOL.mint}>SOL</option>{PRESET_TOKENS.filter(token=>token.mint!==SOL.mint).map(token=><option key={token.mint} value={token.mint}>{token.symbol}</option>)}</select></div><button className="native-reverse" onClick={reverse}>⇅</button><div className="native-token-box"><div><small>You receive</small><strong>{loading?"Loading…":output?compact(output):"0.00"}</strong></div><select className="native-token-select" value={findPreset(to.mint)?.mint??"custom"} onChange={e=>chooseTo(e.target.value)} aria-label="Token to receive">{!findPreset(to.mint)&&<option value="custom">{to.symbol}</option>}{PRESET_TOKENS.filter(token=>token.mint!==SOL.mint).map(token=><option key={token.mint} value={token.mint}>{token.symbol}</option>)}</select></div>{quote&&<div className="native-quote"><span>Price impact</span><strong>{quote.priceImpactPct??"0"}%</strong></div>}{message&&<p className="native-swap-message">{message}</p>}<button className="native-swap-action" onClick={()=>wallet?void execute():void connect()} disabled={loading||swapping}>{swapping?"Confirming swap…":wallet?"Swap now":"Connect Phantom"}</button></section>;
}
