import { useEffect, useMemo, useRef, useState } from "react";
import { Buffer } from "buffer";
import { VersionedTransaction } from "@solana/web3.js";
import "./native-swap.css";

if (!(globalThis as { Buffer?: typeof Buffer }).Buffer) (globalThis as { Buffer?: typeof Buffer }).Buffer = Buffer;

type SwapToken = { symbol:string; name:string; mint:string; decimals:number; logoURI?:string };
type Quote = { inAmount:string; outAmount:string; priceImpactPct?:string; routePlan?:unknown[] } & Record<string, unknown>;
type PhantomProvider = { isPhantom?:boolean; publicKey?:{toString():string}; connect():Promise<{publicKey:{toString():string}}>; signAndSendTransaction?(tx:VersionedTransaction):Promise<{signature:string}|string>; signTransaction?(tx:VersionedTransaction):Promise<VersionedTransaction> };

declare global { interface Window { phantom?:{solana?:PhantomProvider} } }

const SOL:SwapToken={symbol:"SOL",name:"Solana",mint:"So11111111111111111111111111111111111111112",decimals:9};
const USDC:SwapToken={symbol:"USDC",name:"USD Coin",mint:"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",decimals:6};
const API_BASE=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,"")??"https://solpitchswap.kevingpersson.workers.dev";

function toRaw(value:string,decimals:number){const [whole="0",fraction=""]=value.split(".");return (BigInt(whole||"0")*10n**BigInt(decimals)+BigInt(fraction.slice(0,decimals).padEnd(decimals,"0")||"0")).toString();}
function fromRaw(value:string,decimals:number){const padded=value.padStart(decimals+1,"0");const whole=padded.slice(0,-decimals)||"0";const fraction=padded.slice(-decimals).replace(/0+$/g,"");return fraction?`${whole}.${fraction}`:whole;}
function compact(value:string){const n=Number(value);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:6}):"0";}

export default function NativeSwapCard(){
 const [from,setFrom]=useState<SwapToken>(SOL); const [to,setTo]=useState<SwapToken>(USDC); const [amount,setAmount]=useState(""); const [quote,setQuote]=useState<Quote|null>(null); const [loading,setLoading]=useState(false); const [swapping,setSwapping]=useState(false); const [wallet,setWallet]=useState(""); const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [slippage,setSlippage]=useState(50); const debounce=useRef<number|undefined>(undefined);
 const output=useMemo(()=>quote?fromRaw(String(quote.outAmount),to.decimals):"",[quote,to.decimals]);
 useEffect(()=>{window.clearTimeout(debounce.current);setQuote(null);if(!amount||Number(amount)<=0)return;debounce.current=window.setTimeout(async()=>{setLoading(true);setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/quote?inputMint=${from.mint}&outputMint=${to.mint}&amount=${toRaw(amount,from.decimals)}&slippageBps=${slippage}`);const body=await response.json() as Quote&{error?:string};if(!response.ok)throw new Error(body.error||"Quote unavailable");setQuote(body);}catch(error){setMessage(error instanceof Error?error.message:"Quote unavailable");}finally{setLoading(false);}},350);return()=>window.clearTimeout(debounce.current);},[amount,from,to,slippage]);
 async function connect(){const provider=window.phantom?.solana??window.solana;if(!provider?.isPhantom){setMessage("Phantom was not detected.");return;}try{const result=await provider.connect();setWallet(result.publicKey.toString());setMessage("");}catch{setMessage("Wallet connection was cancelled.");}}
 async function findToken(){const mint=search.trim();if(!mint)return;setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/token?mint=${encodeURIComponent(mint)}`);const body=await response.json() as SwapToken&{error?:string};if(!response.ok)throw new Error(body.error||"Token not found");setTo(body);setSearch("");setAmount("");setQuote(null);}catch(error){setMessage(error instanceof Error?error.message:"Token not found");}}
 async function execute(){if(!quote){setMessage("Enter an amount and wait for a quote.");return;}const provider=window.phantom?.solana??window.solana;if(!provider||!wallet){await connect();return;}setSwapping(true);setMessage("");try{const response=await fetch(`${API_BASE}/api/swap/build`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteResponse:quote,userPublicKey:wallet})});const body=await response.json() as {swapTransaction?:string;error?:string};if(!response.ok||!body.swapTransaction)throw new Error(body.error||"Swap transaction unavailable");const tx=VersionedTransaction.deserialize(Buffer.from(body.swapTransaction,"base64"));let signature="";if(provider.signAndSendTransaction){const sent=await provider.signAndSendTransaction(tx);signature=typeof sent==="string"?sent:sent.signature;}else if(provider.signTransaction){const signed=await provider.signTransaction(tx);const sent=await fetch(`${API_BASE}/api/swap/send`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signedTransaction:Buffer.from(signed.serialize()).toString("base64")})});const result=await sent.json() as {signature?:string;error?:string};if(!sent.ok||!result.signature)throw new Error(result.error||"Transaction submission failed");signature=result.signature;}else throw new Error("Phantom cannot sign this transaction.");setMessage(`Swap submitted: ${signature.slice(0,8)}…${signature.slice(-8)}`);setAmount("");setQuote(null);}catch(error){setMessage(error instanceof Error?error.message:"Swap failed");}finally{setSwapping(false);}}
 function reverse(){setFrom(to);setTo(from);setAmount("");setQuote(null);}
 return <section className="native-swap-card"><div className="native-swap-heading"><div><span>SOLPITCH</span><h2>Swap</h2></div><select value={slippage} onChange={e=>setSlippage(Number(e.target.value))}><option value={50}>0.5%</option><option value={100}>1%</option><option value={200}>2%</option></select></div><label className="native-ca-label">Paste CA to select token</label><div className="native-ca-row"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void findToken();}}} placeholder="Solana contract address"/><button onClick={()=>void findToken()}>Find</button></div><div className="native-token-box"><div><small>You pay</small><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,""))} placeholder="0.00" inputMode="decimal"/></div><button className="native-token-pill">{from.logoURI&&<img src={from.logoURI} alt=""/>}{from.symbol}</button></div><button className="native-reverse" onClick={reverse}>⇅</button><div className="native-token-box"><div><small>You receive</small><strong>{loading?"Loading…":output?compact(output):"0.00"}</strong></div><button className="native-token-pill">{to.logoURI&&<img src={to.logoURI} alt=""/>}{to.symbol}</button></div>{quote&&<div className="native-quote"><span>Price impact</span><strong>{quote.priceImpactPct??"0"}%</strong></div>}{message&&<p className="native-swap-message">{message}</p>}<button className="native-swap-action" onClick={()=>wallet?void execute():void connect()} disabled={loading||swapping}>{swapping?"Confirming swap…":wallet?"Swap now":"Connect Phantom"}</button></section>;
}
